# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
#

allow_remote_control yes
   listen_on unix:/tmp/kitty-{kitty_pid}



# --- Padding ---
window_padding_width 12
# You can also set per-side: top right bottom left
# window_padding_width 12 16 12 16

# --- Font ---
font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 13.0

# --- Ligatures ---
disable_ligatures never
