input {
    kb_layout = us
    kb_variant = altgr-intl
    numlock_by_default = false
    repeat_delay = 250
    repeat_rate = 35

    focus_on_close = 1
	

    touchpad {
        natural_scroll = true
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
    }
}

binds {
    scroll_event_delay = 0
}

cursor {
    hotspot_padding = 1
}

# Sensitivity: -1.0 (slow) to 1.0 (fast), 0 = default
input {
    sensitivity = 0.1
    accel_profile = flat    # "flat" = no acceleration, "adaptive" = default
    scroll_method = 2fg
}
